### ISSUE TITLE
automatic vectorization of functional map

### ISSUE THREAD

**Issue by ngoodman** [uber/pyro#100]
if we have a `map` of a referentially transparent function`foo` over a list of Tensors, then it can sometimes be vectorized. vectorization proceeds by packaging the list into a tensor along a new 'batch' dimension and extending the dims of each sample in `foo` appropriately; it is usually faster than the independent application of `foo` to each datum.

however, vectorization is only possible if the computation in `foo` remains data-parallel. rather than establishing this statically (or a priori), i think we can take a JIT approach: assuming sample and param statements return Tensors they can be upgraded to have a batch dim. most pure Tensor operations on the resulting value are 'batch safe' and can be upgraded automatically, but some are 'batch unsafe' (eg because take tensors but return booleans that could flow to control ops). so we can annotate the tensor library with batch safeness. at runtime we assume the computation will be vectorized, and simply bail out (via an exception) if we hit an unsafe operation, defaulting to regular map.

note that this is slightly more general than the front-facing map_data, since it can vectorize other cases of (pure) map. for instance, in #99, continuing execution for each element of the support can be viewed as a map over the support and can often be vectorized.

**Comment by fritzo** [comment]
As I understand, this mostly works using PyTorch broadcasting, which is now supported by `pyro.distributions`: to vectorize, simply append a new batch dimension on the left. We hope to use this form of parallelism in `BranchPoutine` #227 . Closing issue for now since this seems like a feature we get for free by building on PyTorch broadcasting; feel free to reopen if I've misunderstood.
