### ISSUE TITLE
Use pyro for continuous distribution like speech recognition

### ISSUE THREAD

**Issue by pdcoded** [uber/pyro#1434]
Wonder if I can use pyro for cont. distribution like speech. Planning to use it for low resource speech recognition where phonemes are the states. Something like a DNN-HMM model. Any starting point ?

**Comment by eb8680** [comment]
Hi, would you mind posting this question on the [Pyro forum](https://forum.pyro.ai/) instead so that it's easier for others with similar questions to discover?  We prefer to use issues for bugs and Pyro development discussion.

You might find [this forum thread](https://forum.pyro.ai/t/switching-dmm-in-pyro/423/2) about switching deep Markov models relevant to your question.
