### ISSUE TITLE
Sampling from the model without defining model_sample()

### ISSUE THREAD

**Issue by dustinvtran** [uber/pyro#154]
This might be more of a user-related question, but I've noticed that in the current examples, in order to sample from the model or expose some internal execution in the program (such as a VAE's hidden representation before the likelihood draw), you explicitly define a `model_sample()` function. Rewriting many pieces of the model is undesirable for very large neural networks and probabilistic models. Is it possible to directly sample from the `model()` program?

**Comment by martinjankowiak** [comment]
@eb8680 can we close this? do we need to implement more functionality along the lines of inspect? or do we need more examples of the kind of modeling flow raised in this issue in the tutorials?

**Comment by eb8680** [comment]
@martinjankowiak I'll close it.  The solution to this is to use `pyro.condition` instead of hardcoding `observe` within models and to use the `site` kwarg of `pyro.infer.Marginal`.  The two language intro tutorials contain examples of these idioms but they could certainly be documented better and featured more prominently.
