### ISSUE TITLE
More tutorials on Gaussian Processes

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1549]
I think that it is good to have more examples to illustrate the flexibility and the scalable of GP module. I have two examples which come into mind, which I hope that we will have them before next release.

- [ ] Deep Gaussian Process. This is also a good example to illustrate various ways to use `mean_function` and how to use LBFGS.
- [x] Latent variable model. This [paper](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty533/5047752) has various examples on how to use it on pseudotime estimation of cell dataset. This is a good chance to illustrate the usefulness of Reparameterized class.

**Comment by AlejandroCatalina** [comment]
I thought of opening a new issue but I figured this one worked just fine!

First of all I want to congratulate all contributors because pytorch + pyro look really really nice, I'm looking forward to implementing actual models with them!

Nonetheless, I came here looking for a nice probabilistic implementation, and, as always, the first example I look at is the gaussian process. In this regard, I've seen the discussion about adding examples of how to learn the hyper parameters with HMC pop up in plenty of places, but haven't seem the actual examples. Is that because I'm too bad at finding them or because that's a blind spot in the documentation? 

I've seen the HMC tests and tried to run myself a HMC chain to learn the hyper parameters of the GP with no success. My code looks like this:

```python
N = 20
X = dist.Uniform(0.0, 5.0).sample(sample_shape=(N,))
y = 0.5 * torch.sin(3*X) + dist.Normal(0.0, 0.2).sample(sample_shape=(N,))

kernel = gp.kernels.RBF(input_dim=1, variance=torch.tensor(5.),
                        lengthscale=torch.tensor(10.))
gpr = gp.models.GPRegression(X, y, kernel, noise=torch.tensor(1.))

gpr.kernel.set_prior("lengthscale", dist.LogNormal(0.0, 1.0))
gpr.kernel.set_prior("variance", dist.LogNormal(0.0, 1.0))
# we reset the param store so that the previous inference doesn't interfere with this one
pyro.clear_param_store()

hmc_kernel = HMC(gpr.model)
mcmc_run = MCMC(hmc_kernel, num_samples=10000, warmup_steps=2000)
post_trace = defaultdict(list)
for trace, _ in mcmc_run._traces():
    variance_name = param_with_module_name(kernel.name, "variance")
    post_trace["variance"].append(trace.nodes[variance_name]["value"])
    lengthscale_name = param_with_module_name(kernel.name, "lengthscale")
    post_trace["lengthscale"].append(trace.nodes[lengthscale_name]["value"])
```

As you can see, it's pretty much the example code in the documentation, I just replaced the SVI inference section with the HMC chain run. When I learn the parameters with the SVI it works just fine, tuning both lengthscale and variance and also the noise level of the GP. Nonetheless, when I run the HMC I'm only sampling the variance and the lengthscale, and the mean values of the final samples don't look even close to those reached by SVI, which makes sense if I don't learn the noise level parameter, so I guess I'm missing something important related to these questions:

1. How to plug the posterior mean parameter back into the GP? (I would assume that this happens automatically, as it happens when running the SVI)
2. How to properly learn all parameters (including noise level) with HMC, as this completely changes the model? 

Thank you,
Alex

**Comment by fehiepsi** [comment]
Hi Alex, thanks for your question! We have a forum at https://forum.pyro.ai/. If you open a topic there, I am happy to have a throughout discussion with you. For time being, here is what I have in my mind
1. With the old API, you can just simply use `.fix_param(...)` method. With the new API #1544, parameters are parameters of a PyTorch module, so you can change its value as you change the value of a PyTorch parameter. For example,
```
gpr.noise_map.data.copy_(new_value)
```
But you can also simply recreate a new model with learned parameters (as the usual way when using HMC).
2. To learn `noise`, just simply put a prior for it (if you use HMC).

**Comment by AlejandroCatalina** [comment]
Great! I’m opening a topic at the forum so we can have a more detailed discussion. I will address your comments directly there ;).

Thanks!

Best,
Alex

**Comment by AlejandroCatalina** [comment]
I’m having trouble creating an account on the forum (the activation mail doesn’t arrive at all).

Anyway, when I put a prior on the noise to run the HMC algorithm it raises an error
```RuntimeError: Lapack Error in potrf : the leading minor of order 14 is not positive definite at /Users/soumith/miniconda2/conda-bld/pytorch_1532623076075/work/aten/src/TH/generic/THTensorLapack.cpp:626
```
I guess it's triggered from trying a too small noise level and having a singular covariance matrix as a result. Do you have a working example with HMC that I can check out?

Best,
Alex

**Comment by fehiepsi** [comment]
Huhm, what is your prior? Your prior should have a lower bound (say e.g. 1e-6) for `noise` to avoid this singularity. To avoid this confusion, I will make a change in #1544 to always add `jitter` to diagonal of kernel. Thanks for reporting!

**Comment by AlejandroCatalina** [comment]
I set a LogNormal prior, but didn’t know how to set a lower bound. Are there any common priors for noise in pyro?

Thanks!

Best,
Alex

**Comment by fehiepsi** [comment]
@Alex While waiting for #1544, how about using Uniform prior?

**Comment by fehiepsi** [comment]
I have slack account in PyTorch slack (name fehiepsi). I think we'd better discuss there to avoid creating many notifications to other devs.

**Comment by neerajprad** [comment]
> I’m having trouble creating an account on the forum (the activation mail doesn’t arrive at all).

@jpchen ^

**Comment by adam-erickson** [comment]
Quick question - how does one extend the excellent [example](http://pyro.ai/examples/bo.html) on Bayesian optimization to the case where a vector of parameters needs optimization rather than single value? I would ask on the forum, but it's not working for me at the moment.

**Comment by fehiepsi** [comment]
@adam-erickson In BO tutorial, each data point has shape 1. To extend it to a vector of parameters, just simply let each data point has shape `D` (with D is the number of parameters). In other words, `X` will have shape `N x D` in that case.

**Comment by fehiepsi** [comment]
Closed, I will write a blog for deep gaussian process instead.
