### ISSUE TITLE
make test: 13 xfailed

### ISSUE THREAD

**Issue by dbl001** [uber/pyro#534]
I'm on OS X 10.11.6.  I'm running in an Anaconda python 3.6 virtual environment.
(py36) $ python --version
Python 3.6.2 :: Continuum Analytics, Inc.

I ran: make test ...
= 448 passed, 63 skipped, 13 xfailed, 2 xpassed, 1 warnings in 2272.26 seconds =

Here's some of the errors:
```
[gw1] xfail tests/distributions/test_gradient_flow.py::test_bernoulli_with_logits_underflow_gradient[FloatTensor] 
[gw0] xfail tests/infer/test_enum.py::test_bern_elbo_gradient[flat-sum] 
tests/infer/test_enum.py::test_bern_elbo_gradient[flat-sample]
[gw0] xfail tests/infer/test_valid_models.py::test_iarange_wrong_size_error 
```
Any ideas?

**Comment by neerajprad** [comment]
The tests marked with `xfailed` are expected to fail due to various reasons - a feature that is not implemented yet, known bug, etc. For as long as you do not get any 'unexpected' failures, it should be fine. The reason why we have these `xfail` markers is to track bugs or features under development, so that once the issue is resolved, we can see these `xfailing` tests pass again.

**Comment by dbl001** [comment]
Thanks!
