### ISSUE TITLE
Observing deterministically transformed output 

### ISSUE THREAD

**Issue by riedelcastro** [uber/pyro#568]
Thanks for a great library! 

I have the following model (which samples alright):
```python
def add_one_or_two(guess):
    init = 2
    choice = pyro.sample("choice", dist.categorical, ps=guess,vs=[False,True])
    if choice:
        outcome = init + 1
    else:
        outcome = init + 2
    return outcome
```
Now I would like to get a marginal for "choice", after having observed `4` as the output of `add_one_or_two`. It is not 100% clear to me from the [Conditioning on Models](http://pyro.ai/examples/intro_part_ii.html#Conditioning-Models-on-Data) intro how this would look like in this case. Somehow, conditioning seems to be linked to the outputs of `sample` statements but for me, the output of the model is just a deterministic transformation of the `choice` sample. How should I go about this?

**Comment by fritzo** [comment]
Pyro only allows conditioning on sample sites, not on arbitrary deterministic functions of sample sites. This is because conditioning is implemented as a transformation from `pyro.sample` to `pyro.observe`, and observations can only be at sample sites. Pyro has some support for invertible transformations in [TransformedDistribution](http://docs.pyro.ai/transformed_dist.html).

You may be able to workaround this using a [Delta distribution](http://docs.pyro.ai/primitive_dist.html#module-pyro.distributions.delta)
```py
def add_one_or_two(guess):
    ...
    outcome = pyro.sample("outcome", dist.delta, outcome)
    return outcome
```
(but I haven't tried this!)

**Comment by dustinvtran** [comment]
That's an interesting limitation. Most non-trivial implicit models, including physical simulators and GANs, are non-invertible function outputs. It would be nice to support natively both on the poutine side and implemented algorithms side. (Doesn't it also refute the "universal" claim?)

**Comment by riedelcastro** [comment]
Great, thanks! Will give this a go. Don't know how I missed the delta---I tried a categorical with one element in the support, but that didn't fly.

**Comment by eb8680** [comment]
@riedelcastro I'd suggest using a Bernoulli with a very small positive probability of your constraint being false to avoid infinities.

@dustinvtran you can use this Delta/Bernoulli pattern to express conditioning on any Boolean proposition being true, so conditioning in Pyro is in principle as expressive as conditioning in Church, but of course this isn't very efficient because there's no extra information inference algorithms can exploit to improve their chances of satisfying the constraint.  You're right that many interesting models don't have tractable densities, though, and implementing less naive versions of this pattern with ABC likelihoods or discriminators is high on our roadmap.

**Comment by dustinvtran** [comment]
Can you provide a snippet of how that works? For example, say eps ~ N(0, I) for a 10-dimensional noise, followed by x = tanh(eps * W), where W is a 10 x 32 trainable matrix. We observe one 32-dimensional data point x. I don't totally follow how to infer eps. (Note the solution is a deterministic set of points given by the left-inverse of the function.)

**Comment by dustinvtran** [comment]
Oh, got it. In this example, you mean literally doing inference over the joint p(eps, x) = N(eps | 0, 1) I[ x == tanh(eps * W)] and variational distribution q(eps | x).

**Comment by eb8680** [comment]
> In this example, you mean literally doing inference over the joint p(eps, x) = N(eps | 0, 1) I[ x == tanh(eps * W)] and variational distribution q(eps | x)

Yep, although a hard constraint `x == y` on a continuous-valued distribution is false a.s. so in this case you could use a Normal with mean `y` and very small variance as your observation distribution.  This is a very basic version of an ABC likelihood with Gaussian kernel.

**Comment by dustinvtran** [comment]
So I guess the takeaway argument re:universality is that the condition operator holds for continuous non-invertible programs, but the algorithm itself fails because the indicator would almost surely not hold. A Gaussian kernel could work for a naive algorithm in practice although not the same program.

**Comment by eb8680** [comment]
> the algorithm itself fails because the indicator would almost surely not hold

Yeah, see [this paper](https://arxiv.org/abs/1412.4053) for an interesting discussion of the problem of conditioning on rare or complex events.

**Comment by riedelcastro** [comment]
I tried this
```python
def add_one_or_two(guess):
    init = Variable(torch.Tensor([2]))
    choice = pyro.sample("choice", dist.categorical, ps=guess,vs=[False,True])
    if choice:
        outcome = init + 1
    else:
        outcome = init + 2
    return pyro.sample("outcome",dist.delta, outcome)

guess = Variable(torch.Tensor([0.5,0.5]))
conditioned = pyro.condition(
    add_one_or_two, data={"outcome": Variable(torch.Tensor([4]))})
marginal = pyro.infer.Marginal(
    pyro.infer.Importance(conditioned, num_samples=100), sites=["choice"])

marginal(guess)
```

but this gives me

```
RuntimeError: invalid argument 2: invalid multinomial distribution (sum of probabilities <= 0) at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorRandom.c:230
```
Any ideas?

**Comment by fritzo** [comment]
It seems to work to follow @eb8680 's suggestion and add a little noice to the output:
```py
def add_one_or_two(guess):
    init = Variable(torch.Tensor([2]))
    choice = pyro.sample("choice", dist.categorical, ps=guess,vs=[False,True])
    if choice:
        outcome = init + 1
    else:
        outcome = init + 2
    return pyro.sample("outcome", dist.normal, outcome, 0.1 * ng_ones(1))

uess = Variable(torch.Tensor([0.5,0.5]))
conditioned = pyro.condition(add_one_or_two, data={"outcome": Variable(torch.Tensor([4]))})
marginal = pyro.infer.Marginal(pyro.infer.Importance(conditioned, num_samples=100), sites=["choice"])

marginal(guess)
```
```
{'choice': array([False], dtype=bool)}
```

**Comment by ngoodman** [comment]
btw extending the current implemented algorithms to include one that can deal with implicit models (ie observing a stochastically computed value from a function that doesn't come with a scoring function) is one of our next todos. basically, you can use a discriminator as an estimator for the likelihood ratio needed in the elbo. (@dustinvtran and @karalets have both done things like this in papers!) imho this is the right way to extend pyro (as an optimization-focussed ppl) to have something like the `condition` operator of Church etal.

**Comment by N-McA** [comment]
The paper mentioned by @ngoodman is "Hierarchical Implicit Models and
Likelihood-Free Variational Inference" (I believe), available on  [ArXiv](https://arxiv.org/abs/1702.08896 )

**Comment by innuo** [comment]
Even if we can model them with delta or normal with small variance samples, observations that are deterministic transformations of latent variables have another consequence when performing variational inference. 

Assume the model, where we are interested in learning something about mu given observation `x = x0`. (Assume `a` is known and `f` is a deterministic function.)

```
z ~ Normal(mu, a)
x ~ Normal(f(z1), sigma=epsilon, obs=x0)
```

In the guide, the latents can be modeled as being sampled based on other latents or as small deviations of the observed values. 

Either the guide looks something like
```
mu = param
z ~ Normal(mu, a)

```
or
`z ~ Normal(approx_f_inverse(x0), sigma=0.001)`

In the first case, because x0 has negligible probability given guide-sampled z, the convergence is very slow.

The second case doesn't allow learning about mu at all because the sample z doesn't depend on mu.

How can we handle a situation as the one above? Does the likelihood free stuff mentioned above handle this? 

Any pointers on how inference in the above model can be accomplished with Pyro currently?

**Comment by erlebach** [comment]
I had a similar problem, with a variable 
```
 x = pyro.sample("x",  dist.Normal(0., 1.))
 w = 3.
 y = pyro.sample("y", dist.Delta(x*w), obs=x*w)
```

Notice the use of sample as opposed to sampling from a normal distribution of mean _x*y_ and small variance. The difference between the two approaches would be in the guide (for a variational method, which I am using). Using the Delta function, there is no need for a corresponding guide sample. After all, y is observed. The guide must contain the corresponding sample variable if the Normal distribution is used. 

A related question is whether a deterministic function of a sampled variable can be considered as being observed? 

Thanks.
