### ISSUE TITLE
Wrap torch.distributions.* for use in pyro

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#606]
While we work on converging pyro.distributions and torch.distributions, we will need a compatibility layer so that torch.distributions can be used inside Pyro. Ideally this layer will become thinner as we move functionality upstream. As torch.distributions matures, we will remove Pyro's older scipy-based implementations.

- [x] #607 Normal
- [x] #630 Gamma
- [x] #630 Beta
- [x] #630 Dirichlet
- [x] #643 Exponential
- [x] #645 Bernoulli
- [x] #649 Categorical
- [x] #649 OneHotCategorical
- [x] Cauchy
- [x] Uniform
- [x] Multinomial
- [ ] HalfCauchy
- [x] Poisson
- [x] LogNormal
- [x] Binomial
- [ ] Laplace
- [ ] Chi2
- [ ] MultivariateNormal
- [ ] Delta

**Comment by ragulpr** [comment]
Sorry if this is a stupid question, but what will the convergence look like? Are you guys working on porting pyro distributions to torch too? As a small example, I would really prefer pyro-style naming like `mu`, `sigma` to the `mean`, `std` naming style in `torch.distributions.normal` and I'm thinking about submitting a pull request. This also goes with log-likelihood functions/losses in torch like `NLLloss` (bernoulli/cross entropy) etc.

Anyone working on this?

**Comment by fritzo** [comment]
Great question! We and the [Prob Torch](https://github.com/probtorch/probtorch) team are actively moving our distributions code upstream to PyTorch. The converged version will aim to maximize compatibility with TensorFlow Distributions (see their excellent [paper](https://arxiv.org/pdf/1711.10604.pdf)). We're actually leaning towards non-greek names (e.g. loc, scale), but we'd appreciate input if you have good reasons for keeping some names greek.

**Comment by ragulpr** [comment]
I discovered Tensorflow Distributions this week and in trying to figure out what you guys where doing it really opened up a can of worm of awesomeness finding Pyro, Edward etc. Great work!

I think naming is the main reason why statistics/probability is hard so I think it's an extremely important question, not to least because this is going to have big effects on future confusions, research etc. I think we should tap into the infinite wisdom of past practices which it seems from the paper like people are doing so I'm happy you guys are working together. 

I like the location/scale naming when applicable and can see future benefits of sharing properties between such distributions. Is there a place/mailinglist where I can join in on the discussion? I might also be interested in porting in discrete/continuous weibull and maybe and some abstraction for survival analysis but want to get a grip on state of current progress

**Comment by fritzo** [comment]
We communicate on the #distributions channel of the PyTorch slack. You can email Soumith or Adam for an invite.

**Comment by fritzo** [comment]
Closing as mostly done.
