### ISSUE TITLE
Any interest in supporting additional backends (instead of PyTorch)?

### ISSUE THREAD

**Issue by paddyhoran** [uber/pyro#658]
Hi,

As the title asks?  In particular, MXNet could be used I believe.

I wanted to post this in the forum but my log-in has suddenly stopped working and I can't reset it.  Not sure who to contact about that though?

Feel free to close if you feel the discussion should happen in the forum.

Thanks

**Comment by paddyhoran** [comment]
I don't mean that the core devs should add support but rather would they be open to accepting PR's that would do so...

**Comment by eb8680** [comment]
Great question! It's definitely something we've discussed internally, but
it's not currently on our roadmap because some parts of Pyro are tied
closely to pytorch interfaces or semantics. The biggest issue for
contributors interested in this is probably the distributions library -
we're working on moving all our distributions upstream to pytorch, with
standardized interfaces, several custom samplers implemented in C/CUDA, and
uniform broadcasting semantics.

Porting that to mxnet would be quite a lot of work, although it would
probably be of significant independent interest to the mxnet community.

Unfortunately the core team doesn't have the bandwidth for that right now.
Is porting the full distributions library something you'd be interested in
working on? Do you have a particular use case in mind?

If the answer to both of those questions is yes, I can look into what other
internal changes would be necessary and get back to you, but I suspect
adding mxnet support will be much more feasible when the pytorch tensor
interface is closer to numpy/mxnet.ndarray.

**Comment by paddyhoran** [comment]
Thanks @eb8680.

I don't have immediate plans to work on this but I was just trying to get a sense of what the core developers thought.

A common attitude, whether fair or not, is that PyTorch is for "research" and not "production" for some definition of those terms.  MXNet is working toward becoming an Apache project.  The governance etc. that comes along with that can mean something to people looking to invest in an ecosystem and use it in "production".

I love PyTorch but allowing multiple backends in Pyro could be pretty powerful and increase it's adoption.

Thanks for your thoughts, if I get around to trying something out with MXNet or another framework I'll re-open.
