### ISSUE TITLE
Observations that are deterministic functions of latents

### ISSUE THREAD

**Issue by innuo** [uber/pyro#773]
This is a follow-up to 
https://github.com/uber/pyro/issues/568

As was recommended in the discussion of the above issue, even if we can model them with delta or normal with small variance samples, observations that are deterministic transformations of latent variables have another consequence when performing variational inference.

Assume the model, where we are interested in learning something about `mu` given observation `x = x0`. (Assume a is known and `f` is a deterministic function.)

```
z ~ Normal(mu, a)
x ~ Normal(f(z), sigma=epsilon, obs=x0)
```
In the guide, the latents can be modeled as being sampled based on the parameters or as small deviations of the observed values.

Either the guide looks something like

```
mu = param
z ~ Normal(mu, a)
```
or

`z ~ Normal(approx_f_inverse(x0), sigma=epsilon)`

In the first case, because` x0` has negligible probability given guide-sampled `z`, the convergence is very slow.

The second case doesn't allow learning about `mu` at all because the sample `z` doesn't depend on `mu`.

Perhaps this is not an issue but only a consequence of some misunderstanding on my part, but how can I model a situation as the one above? Does the likelihood-free stuff mentioned above handle this?

Any pointers on how inference in the above model can be accomplished with Pyro currently?

**Comment by fritzo** [comment]
If `f` is invertible you can implement it as a `TransformedDistribution`:
```py
class MyTransform(torch.distributions.Transform):
    def _call(self, x):
        ...
    def _inverse(self, y):
        ...
    def log_abs_det_jacobian(self, x, y):
        ...

def model(x0):
    pyro.sample("x", dist.TransformedDistribution(Normal(mu, a), MyTransform()), obs=x0)
```

**Comment by innuo** [comment]
Thanks. That definitely solves the problem by transforming the deterministic function to a sample call. 

Is there a way to do this in case `f` is not invertible? 

This is not an uncommon scenario. For example consider the following model of wind readings from a Met tower.

```
x component of wind vector  = u ~ Normal(mu_x, sigma_x)
y component of wind vector  = v ~ Normal(mu_y, sigma_y)
wind_speed = sqrt(u^2 + v^2)
```
I would like to infer `E[u | wind_speed = w_o]`.

In general are non-invertible transformations disallowed inside Pyro models? 

Please see also my question on the pyro forum: https://forum.pyro.ai/t/variational-inference-with-non-bijective-stochastic-functions/108

**Comment by fritzo** [comment]
> are non-invertible transformations disallowed inside Pyro models?

Correct, Pyro does not allow observation of non-invertible transformation of a random variable. As a workaround you can implement a `Distribution` object that performs your non-invertible transformation and computes `.log_prob()` by integrating over any marginalized-out variables. E.g. in your case you could use a `Chi2` distribution instead of the 2-norm of two `Normal`s; in this case the implementation of `Chi2.log_prob()` effectively integrates over the marginalized-out angle.

**Comment by innuo** [comment]
Is the non-invertibility explicitly checked for? Or does the inference just happen with wrong answers?

The reason I ask is that I was modeling a situation where one latent variable was the maximum of two other latent variables (I used `torch.max()`) and the inference proceeded without errors but gave nonsensical results.

**Comment by eb8680** [comment]
@innuo your example in your first post will work fine with SVI.  If you want to learn about `mu` you'll have to put a prior on it and include a `mu` term in the guide or wrap it in `pyro.param` in the model.

The SVI approximation to the posterior is biased, and may produce incorrect results.  Have you tried `pyro.infer.HMC`?

**Comment by innuo** [comment]
I didn't try HMC, but I did have a prior on `mu`. 

Could you please comment more about my question about the choices about the guides? If `x` is just a delta distribution around `f(z)` how can I pick a guide that is works for inference?

**Comment by innuo** [comment]
@fritzo What I don't really understand is that when there are non-invertible transformations how Pyro goes about computing the log_pdf. 

Essentially my model is specifying sampling according to some  `P_i(x_i | f(x_1, x_2, ..., x_i-1)` where `f` is some arbitrary composition. Could you give me some intuition about the procedure to carry forward the computation of the log-pdf `log P(x_i , x_1, x_2, ..., x_i-1)`

**Comment by eb8680** [comment]
@innuo I think you may be getting caught up in notation.  If `x` is a delta around `f(z)` and you give it a Gaussian likelihood with a small `sigma`, that's just an ABC likelihood for `x`, which is a new random variable `y` in Pyro.  Pyro never computes the marginal density of `x`, just the sum of the trivial delta conditional and Gaussian approximate likelihood for `y`.  Random variables at sample statements are expected to have tractable conditional densities, so that the log-joint is just a sum of all the log-conditionals.

Re: guide choice, your intuition about choosing an approximate inverse of `f` is correct.  The second case in your first post actually does allow learning `mu` through the prior term in the ELBO `log p(z; mu)`.

**Comment by innuo** [comment]
@eb8680 I don't think I follow yet. I must be missing some crucial insight.

Here is a runnable Pyro code to demonstrate what I am doing. I would appreciate it if you could point out why neither of these two guides (which follow the patterns in my original post) work for inferring `mu` in my model.

(I tried to find the simplest example to illustrate the issue. I understand that I could eliminate the need for the z_i variables in my code by reparameterizing x_i)

```
def model(data, sigma):
    mu = pyro.sample("mu", dist.uniform, Variable(torch.Tensor([0])), Variable(torch.Tensor([20])))

    for i in range(len(data)):
        z_i = pyro.sample("z_{}".format(i), dist.normal, mu, Variable(torch.Tensor([sigma])))

        #x = 2 * z which is modeled with a normal with small variance
        pyro.sample("x_{}".format(i), dist.normal, 2*z_i, Variable(torch.Tensor([0.01])),
                    obs=Variable(torch.Tensor([data[i]])))


def guide1(data, sigma):
    mu_mean = pyro.param("mu_mean", Variable(torch.Tensor([15]), requires_grad=True))
    mu_sigma = pyro.param("mu_sigma", Variable(torch.Tensor([np.log(.1)]), requires_grad=True))

    mu = pyro.sample("mu", dist.normal, mu_mean, torch.exp(mu_sigma))

    for i in range(len(data)):
        z_i = pyro.sample("z_{}".format(i), dist.normal, mu, Variable(torch.Tensor([sigma])))


def guide2(data, sigma):
    mu_mean = pyro.param("mu_mean", Variable(torch.Tensor([15]), requires_grad=True))
    mu_sigma = pyro.param("mu_sigma", Variable(torch.Tensor([np.log(.1)]), requires_grad=True))

    mu = pyro.sample("mu", dist.normal, mu_mean, torch.exp(mu_sigma))

    for i in range(len(data)):
        z_i = pyro.sample("z_{}".format(i), dist.normal, Variable(torch.Tensor([0.5 * data[i]])), Variable(torch.Tensor([0.01])))


if __name__ == '__main__':
    #Generate some data
    mu = 10 #unknown
    sigma = 2 #known
    N =  20  # size of the data
    data = np.random.normal(mu, sigma, N)

    adam_params = {"lr": 0.01, "betas": (0.90, 0.999)}
    optimizer = Adam(adam_params)

    svi = SVI(model, guide2, optimizer, loss="ELBO", num_particles=10)

    losses = []
    for step in range(1000):
        losses.append(svi.step(data, sigma))

    a = pyro.get_param_store()
    print(a._params)
```

**Comment by eb8680** [comment]
> I understand that I could eliminate the need for the z_i variables in my code by reparameterizing x_i

But this is probably the primary reason it's not working - you're doing biased approximate inference in a noisy approximation to your true model.  If you want higher quality inference, you'll have to reduce bias and variance.  You can remove bias in inference by using HMC, and you can remove the variance in your model approximation entirely by writing the true likelihood as a Pyro `Distribution` and eliminating those `z_i` variables.  

Otherwise, you can try tuning hyperparameters like parameter initialization, ABC kernel bandwidth, and learning rate.  SVI can unfortunately be rather finicky, even in systems like Stan which limit the universe of possible models and focus much more on truly automated inference.

**Comment by innuo** [comment]
@fritzo @eb8680 Thanks for your replies. I think I have a much better understanding of the limitations of variational inference and how to circumvent them in Pyro. 

I think it might make sense to add a section on modeling "Observations that are deterministic functions of latents" or some such to the Pyro tutorials. This is an important class of models and other users may have the same questions I did. 

It might also be useful to provide some guidance in the tutorials on non-invertible transformations in Pyro models.

**Comment by eb8680** [comment]
> It might also be useful to provide some guidance in the tutorials on non-invertible transformations in Pyro models.

Agreed, we may do that as we add algorithms aimed at that class of problems (e.g. [LFVI](http://papers.nips.cc/paper/7136-hierarchical-implicit-models-and-likelihood-free-variational-inference.pdf)).  Contributions are welcome in the meantime!

**Comment by rachtsingh** [comment]
I think I roughly understand the above discussion (@eb8680 , your comment about ABC made a lot of sense to me).

However, @fritzo's example as given [here](https://github.com/uber/pyro/issues/568#issuecomment-344152751) (copied below) doesn't work anymore since Pyro has changed a lot. Could someone translate that example?

```python
def add_one_or_two(guess):
    init = Variable(torch.Tensor([2]))
    choice = pyro.sample("choice", dist.categorical, ps=guess,vs=[False,True])
    if choice:
        outcome = init + 1
    else:
        outcome = init + 2
    return pyro.sample("outcome", dist.normal, outcome, 0.1 * ng_ones(1))

guess = Variable(torch.Tensor([0.5,0.5]))
conditioned = pyro.condition(add_one_or_two, data={"outcome": Variable(torch.Tensor([4]))})
marginal = pyro.infer.Marginal(pyro.infer.Importance(conditioned, num_samples=100), sites=["choice"])

marginal(guess)
```

Things I struggled with trying to convert it:
1. `Categorical` doesn't have `vs` anymore, so the line `if choice:` keeps failing, since either choice seems to vary from between multidimensional to 0-dimensional during runtime.
2. Trying to sidestep that issue by doing something a little incorrect (conditioning on `choice.sum()`) raises a model issue, which I think might be a bug

If it helps I tried to use HMC here, since that's what @eb8680 recommended a few posts up. Here's the stacktrace from 2:

```python
...pyro/infer/mcmc/util.py in _populate_cache(self, model_trace)
    170             raise ValueError("Finite value required for `max_plate_nesting` when model "
    171                              "has discrete (enumerable) sites.")
--> 172         model_trace.compute_log_prob()
    173         model_trace.pack_tensors()
    174         for name, site in model_trace.nodes.items():

...pyro/poutine/trace_struct.py in compute_log_prob(self, site_filter)
    161                 if "log_prob" not in site:
    162                     try:
--> 163                         log_p = site["fn"].log_prob(site["value"], *site["args"], **site["kwargs"])
    164                     except ValueError:
    165                         _, exc_value, traceback = sys.exc_info()

TypeError: log_prob() takes 2 positional arguments but 3 were given
```

Thanks!

**Comment by fritzo** [comment]
I haven't tried running this but here is an attempted translation:
```py
def add_one_or_two(guess):
    init = torch.tensor(2.)
    choice = pyro.sample("choice", dist.Categorical(ps=guess))
    if choice:
        outcome = init + 1
    else:
        outcome = init + 2
    return pyro.sample("outcome", dist.Normal(outcome, 0.1 * ng_ones(1)))

guess = torch.tensor([0.5,0.5])
```
I'm not sure about the rest, @eb8680 does this look right?
```py
conditioned = pyro.condition(add_one_or_two, data={"outcome": torch.tensor(4.)})
marginal = pyro.infer.EmpiricalMarginal(
    pyro.infer.Importance(conditioned, num_samples=100), sites=["choice"])
marginal(guess)
```

**Comment by eb8680** [comment]
@rachtsingh I'm not sure what you're looking for, can you be more specific?  What do you mean by failed?  In general, to apply the ABC trick, just add an auxiliary variable in your model and proceed in the usual way:
```python
def model(data):
    ...
    deterministic_value = determinsitic_fn(stuff)
    abc_bandwidth = torch.tensor(1e-2)
    abc_dist = Normal(loc=deterministic_value, scale=abc_bandwith).to_event(len(deterministic_value.shape))
    pyro.sample("constrained_value", abc_dist, obs=data)
    ...
```
Note that if `data` is very different from `deterministic_value`, inference will be necessarily be difficult because the data is very unlikely under the approximate model and will take a long time to converge and generally be noisy and unstable.  If `deterministic_fn` is invertible, you should use a `TransformedDistribution` to compute the likelihood term `p(data | observed_value, ...)` exactly.

**Comment by rachtsingh** [comment]
Ok, I think I pretty much understand now. Here's a complete working example:

```python
def model(data):
    init = torch.tensor(2.)
    choice = pyro.sample("choice", dist.Categorical(probs=torch.tensor([0.5, 0.5])))
    if choice:
        outcome = init + 1
    else:
        outcome = init + 2
    abc_dist = dist.Normal(loc=outcome, scale=torch.tensor(0.1))
    return pyro.sample("outcome", abc_dist, obs=data)
data = torch.tensor(4.)
importance = pyro.infer.Importance(model, num_samples=100).run(data)
marginal = pyro.infer.EmpiricalMarginal(importance, "choice")
```

If I understand correctly - the guide (here just the prior) provides a distribution that we sample from, pass through the deterministic function, and then evaluate the ABC likelihood on the data, which here is easy since it's ~0 for choice = 1, and something positive for choice = 0. Just to clarify, `importance` then corresponds to the distribution which samples from `{0, 1}` with importance sampling weights (I think I confirmed this with some experiments). I don't quite understand how this works with HMC, but I think I can probably figure this out.

Sorry about the lack of specific example until now - I had one in mind but I wanted to understand the general principle. Essentially we have a parameter `p` I'd like to fit, such that `x ~ Dist(param=p)` for some distribution `Dist`. And then we observe `f(x)` where `f` is a deterministic function. We should be able to get a posterior distribution over `p` using ABC here, right? I just need to add an `abc_dist = Normal(f(x), bandwidth)` and observe that.

The point you make above is essentially saying that if the probability of the right `p` under the prior is low, then we will sort of blind about what's possible. If performance isn't an issue, then in 1D we can counteract this by taking many samples from the prior.

Thanks for the help! Please let me know if I've got something wrong.
