### ISSUE TITLE
Including build metadata for Pyro versioning

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#921]
@fritzo suggested that it might be a good idea to include build metadata in Pyro version, as PyTorch does. This will easily help pin the Pyro version used, say in jupyter notebook, by running `pyro.__version__` at the top of the file. 

A reasonable format for this could be what we already have, plus some other information, that follows the [semantic versioning](https://semver.org/) specs. In particular, we could use the format:
`major.minor.patch-{tag}+{build-metadata}`.
 - `major.minor.patch` is the same as what we have right now and can just be specified as a string in the `pyro/__init__.py` file.
 - `tag` denotes optional pre-release version and may indicate that the compatibility requirements expected from `major.minor.patch` may not be satisfied (if its an alpha release). Could be `alpha`. PyTorch uses `a0`.
 - `build-metadata` - This has additional build specific metadata, and what we might want to include in our version info. It could just be the shortened sha commit id. Additionally, it could have the following information:
   - `.pytorch-{pytorch-sha-commit}` - this may be debatable, as `torch.__version__` should give us this info.
   - `.dirty` to indicate that the user has uncommitted changes. e.g. if a notebook has `.dirty`, it will indicate that you may not be able to replicate the results by simply using the sha commit id indicated by the version, as the user has modified pyro source code.

The full version string might look like - `0.1.2-a0+e581401.pytorch-a58f2d2.dirty`. Let me know your thoughts, preferences etc.?

**Comment by neerajprad** [comment]
cc. @fritzo, @jpchen.

**Comment by fritzo** [comment]
@jpchen What do you think? I think this would be useful for two reasons:
- Users could paste a useful `pyro.__version__` in github issues
- We could add a version header to the top of all internal notebooks (e.g. our pyro_model.ipynb):
    ```py
    import torch
    import pyro
    print(torch.__version__)
    print(pyro.__version__)
    ```

**Comment by jpchen** [comment]
this is a great idea! ive personally found it cumbersome to check which pyro version im using since they all default to the latest release tag. for some of your specific suggestions:
> tag denotes optional pre-release version

why is this needed? cant all that information be inferred from the semver version? seems like these prerelease tags are informal and dont convey additional information

>`.pytorch-{pytorch-sha-commit}`

i would prefer not to have this since it overloads the version and like you said, can be elicited by running `torch.__version__`. i like something like:
```
> import pyro
> pyro.__version__
0.1.2+e581401[-dirty]
```
with `dirty` being if the pyro workspace is dirty. thoughts?

**Comment by neerajprad** [comment]
> why is this needed? cant all that information be inferred from the semver version? seems like these prerelease tags are informal and dont convey additional information

I agree. There is not much information in there except, "this is an alpha release. we might break semantic versioning compatibility from time to time" :). I am fine with skipping this, and the pytorch sha id too.

**Comment by fritzo** [comment]
> why is [the pre-release tag] needed?

I believe the pre-release tag is needed for correct partial-ordering of versions.

I'm currently favoring the following semver-compliant version format: 
```py
>>> print(pyro.__version__)
'0.2.0-a0+72e07e20'
```
This includes three parts:
- release major.minor.patch
- `-a0` indicates that this is pre-0.2.0 release (and will be removed after 0.2 release)
- `+72e07e20` indicates the sha1 hash of the Pyro git version

It seems clearer to me to name today's version by `0.2.0-a0+72e07e20` rather than `0.1.2+72e07e20` since today Pyro is much closer to 0.2 than 0.1.2 (and because it uses PyTorch 0.4 prerelease rather than PyTorch 0.3). Thoughts?

**Comment by neerajprad** [comment]
> -a0 indicates that this is pre-0.2.0 release (and will be removed after 0.2 release)

I was under the impression that we were using `0.x.x` to denote that this is pre-release. Not that I mind this additional indirection. :)

**Comment by neerajprad** [comment]
> It seems clearer to me to name today's Pyro version by 0.2.0-a0+72e07e20 rather than 0.1.2+72e07e20 since today Pyro is much closer to 0.2 than 0.1.2 (and because it uses PyTorch 0.4 prerelease rather than PyTorch 0.3).

That sounds reasonable. We will still continue to retain `a0` once we start using PyTorch 0.4 release officially, right?

**Comment by fritzo** [comment]
> I was under the impression that we were using `0.x.x` to denote that this is pre-release

By pre-release I mean "code just before release x.y.z". We've already had a 0.1.2 release. We have not yet had a 0.2.0 release. Pyro codebase is now closer to the planned 0.2.0 release than it is to the previous 0.1.2 release. I think it is confusing that `pyro.__version__` in dev is still the string release string '0.1.2'. I think it would be easier to understand if we set `pyro.__version__` to 0.2.0-something even before the 0.2.0 release. The "something" should indicate that the code is pre-0.2.0-release. Semver convention is to use the string `asomething` to denote pre-release.

**Comment by fritzo** [comment]
We will drop the `-a0` when we release.

**Comment by neerajprad** [comment]
> The "something" should indicate that the code is pre-0.2.0-release. 

Okay, that clarifies in what context `a0` is being used, and sounds very reasonable. I was confused because PyTorch retains `a0` throughout, even for officially released versions on pytorch.org.
